# Cleaning the Dataset
## In this notebook, we removed all the datapoints with null values, as well as removing all datapoints that had less than 500 reviews.

In [2]:
# Importing dependecies
import pandas as pd
from pathlib import Path
from pprint import pprint

In [3]:
# Naming the file path
file = Path('wines_SPA.csv')

In [4]:
# Checking the encoding of the csv - got code from https://stackoverflow.com/questions/37177069/how-to-check-encoding-of-a-csv-file#:~:text=The%20evaluated%20encoding%20of%20the,looking%20in%20the%20drop%20down.
with open('wines_SPA.csv') as f:
    print(f)

<_io.TextIOWrapper name='wines_SPA.csv' mode='r' encoding='cp1252'>

In [5]:
# Reading in the CSV file
wine_df = pd.read_csv(file, encoding ='cp1252')

In [6]:
# Viewing columns for reference
wine_df.columns

Index(['winery', 'wine', 'year', 'rating', 'num_reviews', 'country', 'region',
       'price', 'type', 'body', 'acidity'],
      dtype='object')

In [7]:
# Counting the number of values in each column to see if there are null values. 
wine_df.count()

winery         7500
wine           7500
year           7498
rating         7500
num_reviews    7500
country        7500
region         7500
price          7500
type           6955
body           6331
acidity        6331
dtype: int64

In [10]:
# Dropping all null values
wine_clean_df = wine_df.dropna()

# Checking the count to make sure there are no null values.
wine_clean_df.count()

winery         6329
wine           6329
year           6329
rating         6329
num_reviews    6329
country        6329
region         6329
price          6329
type           6329
body           6329
acidity        6329
dtype: int64

In [11]:
# Removing all the wines that had less than 500 reviews
wine_reduced_clean = wine_clean_df[wine_clean_df['num_reviews'] >= 500]
wine_reduced_clean

,winery,wine,year,rating,num_reviews,country,region,price,type,body,acidity
2,Vega Sicilia,Unico,2009,4.8,1793,Espana,Ribera del Duero,324.95,Ribera Del Duero Red,5.0,3.0
3,Vega Sicilia,Unico,1999,4.8,1705,Espana,Ribera del Duero,692.96,Ribera Del Duero Red,5.0,3.0
4,Vega Sicilia,Unico,1996,4.8,1309,Espana,Ribera del Duero,778.06,Ribera Del Duero Red,5.0,3.0
5,Vega Sicilia,Unico,1998,4.8,1209,Espana,Ribera del Duero,490.00,Ribera Del Duero Red,5.0,3.0
6,Vega Sicilia,Unico,2010,4.8,1201,Espana,Ribera del Duero,349.00,Ribera Del Duero Red,5.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...
1971,Fernando de Castilla,Antique Palo Cortado,N.V.,4.2,519,Espana,Jerez Palo Cortado,36.90,Sherry,4.0,3.0
1972,Matsu,El Viejo,2017,4.2,518,Espana,Toro,33.90,Toro Red,5.0,3.0
1973,Lan,Vina Lanciano Reserva,2015,4.2,514,Espana,Rioja,14.60,Rioja Red,4.0,3.0
1974,Anima Negra,An,2016,4.2,513,Espana,Mallorca,139.90,Red,4.0,3.0
1975,Bodegas Mas Alta,Artigas,2017,4.2,505,Espana,Priorato,20.90,Priorat Red,4.0,3.0

In [14]:
# Renaming the Index column
wine_reduced_clean.index.names = ['id']
wine_reduced_clean.head()

,winery,wine,year,rating,num_reviews,country,region,price,type,body,acidity
id,,,,,,,,,,,
2,Vega Sicilia,Unico,2009,4.8,1793,Espana,Ribera del Duero,324.95,Ribera Del Duero Red,5.0,3.0
3,Vega Sicilia,Unico,1999,4.8,1705,Espana,Ribera del Duero,692.96,Ribera Del Duero Red,5.0,3.0
4,Vega Sicilia,Unico,1996,4.8,1309,Espana,Ribera del Duero,778.06,Ribera Del Duero Red,5.0,3.0
5,Vega Sicilia,Unico,1998,4.8,1209,Espana,Ribera del Duero,490.00,Ribera Del Duero Red,5.0,3.0
6,Vega Sicilia,Unico,2010,4.8,1201,Espana,Ribera del Duero,349.00,Ribera Del Duero Red,5.0,3.0

In [15]:
# Rechecking other aspects of the reduced data set, like number of wineries and the number of regions.
wine_reduced_clean.nunique()['winery']

112

In [16]:
# Saving the cleaned data to a CSV file.
wine_reduced_clean.to_csv("spanish_wine_cleaned.csv")

In [17]:
# Saving cleaned data to a JSON file. 
wine_reduced_clean.to_json("spanish_wine.json", orient="index")